<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maria Clara Figueiredo Coelho e Victória Raspante Marques">

<title>Relatório de Aula Prática 02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> 📌 Introdução</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">2</span> 🎯 Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-geral" id="toc-objetivo-geral" class="nav-link" data-scroll-target="#objetivo-geral"><span class="header-section-number">2.1</span> Objetivo geral</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos específicos</a></li>
  </ul></li>
  <li><a href="#metodologia" id="toc-metodologia" class="nav-link" data-scroll-target="#metodologia"><span class="header-section-number">3</span> ⚙️ Metodologia</a></li>
  <li><a href="#resultados-e-discussão" id="toc-resultados-e-discussão" class="nav-link" data-scroll-target="#resultados-e-discussão"><span class="header-section-number">4</span> 🔍 Resultados e Discussão</a>
  <ul class="collapse">
  <li><a href="#importação-do-banco-de-dados" id="toc-importação-do-banco-de-dados" class="nav-link" data-scroll-target="#importação-do-banco-de-dados"><span class="header-section-number">4.1</span> Importação do banco de dados</a></li>
  <li><a href="#investigação-e-limpeza-dos-dados" id="toc-investigação-e-limpeza-dos-dados" class="nav-link" data-scroll-target="#investigação-e-limpeza-dos-dados"><span class="header-section-number">4.2</span> Investigação e Limpeza dos Dados</a></li>
  <li><a href="#exploração-dos-dados" id="toc-exploração-dos-dados" class="nav-link" data-scroll-target="#exploração-dos-dados"><span class="header-section-number">4.3</span> Exploração dos dados</a></li>
  </ul></li>
  <li><a href="#considerações-finais" id="toc-considerações-finais" class="nav-link" data-scroll-target="#considerações-finais"><span class="header-section-number">5</span> 🧠 Considerações finais</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><span class="header-section-number">6</span> 📖 Referências</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<div class="logos" style="display: flex; justify-content: center; align-items: center; height: 200px; gap: 20px;">

  <a href="https://ufsj.edu.br">

    <img src="imagens/ufsj.png" width="220px">

  </a>

  <a href="https://ufsj.edu.br/defim">

    <img src="imagens/defim.png" width="220px">

  </a>

</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Relatório de Aula Prática 02</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
<p class="subtitle lead"><a href="https://bendeivide.github.io/courses/epaec/" target="_blank">Estatística e Probabilidade</a> <br> <a href="https://bendeivide.github.io" target="_blank">Prof.&nbsp;Ben Dêivide (DEFIM/CAP/UFSJ)</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Maria Clara Figueiredo Coelho e Victória Raspante Marques </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">31/08/2026, 03:37</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">1</span> 📌 Introdução</h2>
<p>A análise de dados é uma ferramenta de grande valor para o acompanhamento e o controle de qualidade dos materiais empregados nas obras, no âmbito da Engenharia Civil. No controle tecnológico do concreto, informações como resistência à compressão, abatimento, relação água/cimento e idade dos corpos de prova auxiliam na avaliação do desempenho do material e na identificação de possíveis resultados fora do comportamento esperado.</p>
<p>Entretanto, dados obtidos em ensaios, registros de campo e planilhas podem apresentar valores ausentes, erros de digitação e inconsistências de preenchimento. Por esse motivo, antes da realização das análises estatísticas, é importante verificar a qualidade dos registros e realizar os tratamentos necessários para garantir maior confiabilidade aos resultados.</p>
<p>Nesse contexto, este relatório utilizará a linguagem R para inspecionar, tratar e explorar uma base de dados relacionada ao controle tecnológico do concreto, buscando transformar os dados brutos em informações úteis para sua análise e interpretação.</p>
</section>
<section id="objetivos" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="objetivos"><span class="header-section-number">2</span> 🎯 Objetivos</h2>
<section id="objetivo-geral" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="objetivo-geral"><span class="header-section-number">2.1</span> Objetivo geral</h3>
<p>Processar e analisar uma base de dados referente ao controle tecnológico do concreto, utilizando a linguagem R para identificar e tratar inconsistências e obter informações relevantes para a interpretação dos resultados.</p>
</section>
<section id="objetivos-específicos" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos específicos</h3>
<ul>
<li>Inspecionar a estrutura e as características da base de dados;</li>
<li>Identificar valores ausentes, erros de digitação e possíveis inconsistências;</li>
<li>Padronizar e tratar as variáveis para realização das análises;</li>
<li>Aplicar recursos da linguagem R para manipulação e exploração dos dados;</li>
<li>Calcular e comparar resultados relacionados às propriedades do concreto;</li>
<li>Investigar relações entre variáveis relevantes para o controle tecnológico;</li>
<li>Interpretar os resultados obtidos considerando sua aplicação na Engenharia Civil.</li>
</ul>
<hr>
</section>
</section>
<section id="metodologia" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metodologia"><span class="header-section-number">3</span> ⚙️ Metodologia</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Descreva como o experimento foi realizado.</p>
</div>
</div>
<ul>
<li>Materiais utilizados<br>
</li>
<li>Procedimento<br>
</li>
<li>Número de repetições</li>
</ul>
<hr>
</section>
<section id="resultados-e-discussão" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="resultados-e-discussão"><span class="header-section-number">4</span> 🔍 Resultados e Discussão</h2>
<section id="importação-do-banco-de-dados" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="importação-do-banco-de-dados"><span class="header-section-number">4.1</span> Importação do banco de dados</h3>
<p>A base de dados foi importada para o R através da função <code>read.csv2()</code> e atribuída a <code>dados</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"base_processamento_dados_engenharia_civil.csv"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    id_corpo_prova     obra tipo_concreto idade_dias resistencia_mpa
1           CP-001  Bloco A           C35         28            36.3
2           CP-002  Bloco A           C30          7            28.4
3           CP-003  Bloco C           C30         56            36.1
4           CP-004  Bloco A           C40         28            47.2
5           CP-005  Bloco B           C25         28            27.9
6           CP-006  Bloco B           C40         28            41.5
7           CP-007  Bloco C           C25         56            23.7
8           CP-008  Bloco D           C30         28            38,7
9           CP-009  Bloco B           C30         14            30.3
10          CP-010  Bloco A           C25          7            25.3
11          CP-011  Bloco C           C30          7            31.8
12          CP-012  Bloco A           C40         28            39.4
13          CP-013  Bloco B           C35         28            35.6
14          CP-014  Bloco B           C35         28            39.4
15          CP-015  Bloco B           C35         14            36.3
16          CP-016  Bloco A           C25         28            28.7
17          CP-017  Bloco B           C35         14            38.4
18          CP-018  Bloco B           C30         28            34.7
19          CP-019  Bloco B           C30         28            3O,4
20          CP-020  Bloco B           C40         14            41.7
21          CP-021  Bloco A           C30         28            28.8
22          CP-022  Bloco C           C40         28            45.2
23          CP-023  Bloco C           C30         28            35.5
24          CP-024  Bloco A           C40         28            44.7
25          CP-025  Bloco A           C25         28            27.2
26          CP-026  Bloco C           C25          7            24.4
27          CP-027 Bloco B            C30         28            39.4
28          CP-028  Bloco D           C30         28            33.6
29          CP-029  Bloco D           C25          7            23.7
30          CP-030  Bloco B           C35         56            44.6
31          CP-031  Bloco D           C35         28            40.7
32          CP-032  Bloco D           C35         14            36.6
33          CP-033  Bloco C           C30         28            31.5
34          CP-034  Bloco C           C30          7            28.7
35          CP-035  Bloco B           C35         56            41.1
36          CP-036  Bloco C           C30          7            24.5
37          CP-037  Bloco B           C30         56            36.6
38          CP-038  Bloco C           C25         28            25.7
39          CP-039  Bloco C           C40         28            44.9
40          CP-040  Bloco B           C25         28            29.4
41          CP-041  Bloco D           C25         28            31.4
42          CP-042  Bloco B           C30         56            32.3
43          CP-043  Bloco A           C35         14            33.9
44          CP-044  Bloco C           C25         28            23.6
45          CP-045  Bloco C           C40         14            42.9
46          CP-046  Bloco D           C30         28            31.8
47          CP-047  Bloco B           C25         28            26.2
48          CP-048  Bloco B           C30          7            32.1
49          CP-049  Bloco A           C40         28            38.8
50          CP-050  Bloco C           C30         14            32.7
51          CP-051  Bloco C           C30         28            33.1
52          CP-052  Bloco C           C25          7            31.6
53          CP-053  Bloco D           C30         28            27.4
54          CP-054  Bloco A           C40          7            42.5
55          CP-055  Bloco D           C25         28            28.2
56          CP-056  Bloco B           C35         28            37.9
57          CP-057  Bloco B           C30         56            33.5
58          CP-058  Bloco D           C35         14            33.7
59          CP-059  Bloco B           c30          7            29.9
60          CP-060  Bloco A           C25         28            29.3
61          CP-061  Bloco C           C25         28            29.3
62          CP-062  Bloco A           C25         28            29.5
63          CP-063  Bloco B           C35         28            36.2
64          CP-064  Bloco A           C30          7            25.6
65          CP-065  Bloco C           C30         28            35.6
66          CP-066  Bloco C           C35         28            41.6
67          CP-067  Bloco C           C30         14            29.6
68          CP-068  Bloco A           C30          7            30.7
69          CP-069  Bloco C           C35         28            33.6
70          CP-070  Bloco A           C25         28            29.8
71          CP-071  Bloco A           C30         28            31.0
72          CP-072  Bloco B           C40         14            37.3
73          CP-073  Bloco D           C40         28            46.5
74          CP-074  Bloco B           C25         28            27.8
75          CP-075  Bloco A           C35         28            41.8
76          CP-076  Bloco A           C25         56            26.6
77          CP-077  Bloco D           C25         14            19.0
78          CP-078  Bloco C           C40         28            46.9
79          CP-079  Bloco D           C30         28            29.9
80          CP-080  Bloco B           C35         28            35.1
81          CP-081  Bloco B           C40         28            47.5
82          CP-082  Bloco D           C40         14            43.4
83          CP-083  Bloco C           C25         28            28.0
84          CP-084  Bloco C           C25         28            23.3
85          CP-085  Bloco A           C30        280            38.3
86          CP-086  Bloco C           C35          7            30.1
87          CP-087  Bloco A           C25         56            27.8
88          CP-088  Bloco B           C35         28            36.9
89          CP-089  Bloco C           C25         14            28.3
90          CP-090  Bloco C           C30         28            33.1
91          CP-091  Bloco B           C35         28            39.6
92          CP-092  Bloco B           C35         14                
93          CP-093  Bloco A           C40         28            42.9
94          CP-094  Bloco A           C35          7            29.9
95          CP-095  Bloco A           C25         28            30.3
96          CP-096  Bloco D           C25          7            21.3
97          CP-097  Bloco A           C25         28            26.7
98          CP-098  Bloco A           C35         14            37.0
99          CP-099  Bloco C           C25         56            31.1
100         CP-100  Bloco A           C30         56            30.9
    cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
1             395         0.5         111.0          2332.0
2             340        0.54         114.0          2389.0
3             338        0.56         106.0          2427.0
4             407        0.47         142.0          2345.0
5             316        0.61         133.0          2448.0
6             398        0.43          98.0          2324.0
7             351        0.65          99.0          2385.0
8             347        0.54         116.0          2387.0
9             346        0.54         125.0          2328.0
10            315         0.6         127.0          2413.0
11            340        0.58          95.0          2374.0
12            396        0.44         114.0          2374.0
13            379         0.5         123.0          2339.0
14            394        0.52         121.0          2372.0
15            363        0.49                        2359.0
16            325         0.6         175.0          2326.0
17            363        0.52         109.0          2348.0
18            344        0.56         118.0          2414.0
19            356        0.59          83.0          2360.0
20            412        0.48         107.0          2378.0
21            361        0.58         116.0          2451.0
22            409        0.48         113.0          2360.0
23            343        0.54         101.0          2363.0
24            418        0.45         124.0          2363.0
25            302        0.62         107.0          2381.0
26            307        0.63         112.0          2364.0
27            365        0.57         102.0          2413.0
28            343        0.58         104.0          2324.0
29            330        0.63         100.0          2347.0
30            378        0.56         122.0          2386.0
31            381        0.54         103.0          2387.0
32            370        0.53        1250.0          2383.0
33            344        0.54         132.0          2374.0
34            345        0.58         110.0          2345.0
35            381         0.5         103.0          2324.0
36            355        0.56          93.0          2373.0
37            369        0.55         118.0          2380.0
38            309                     146.0          2334.0
39            404        0.46         120.0          2385.0
40            345        0.62          89.0          2401.0
41            317        0.61         100.0          2390.0
42            351        0.56         108.0          2385.0
43            356        0.51         107.0          2293.0
44            327        0.61         127.0          2396.0
45            407        0,55          76.0          2381.0
46            342        0.59         131.0          2434.0
47            325        0.65          83.0          2325.0
48            351        0.59         127.0          2390.0
49            414        0.48         103.0          2376.0
50            355        0.57         142.0          2344.0
51            352        0.55          82.0          2316.0
52            318        0.64          93.0          2354.0
53            349        0.61          97.0           238.0
54            395        0.51          71.0          2391.0
55            320        0.59         143.0          2405.0
56            368         0.5         108.0          2376.0
57            341        0.59          85.0          2402.0
58            389        0.53          70.0          2387.0
59            340        0.58          95.0          2388.0
60            340        0.63         100.0          2363.0
61            301        0.62         103.0          2357.0
62            344        0.63          97.0          2350.0
63            385        0.51          99.0          2358.0
64           390O        0.59         114.0          2427.0
65            353        0.57         111.0          2334.0
66            372        0.51         110.0          2378.0
67            337        0.57         136.0          2362.0
68            346        0.56         126.0          2460.0
69            390        0.46         123.0          2360.0
70            345        0.63         117.0          2381.0
71            352        0.59         103.0          2383.0
72            403        0.48          98.0          2414.0
73            399        0.44          81.0          2315.0
74            300        0.62         114.0          2378.0
75            362        0.46          64.0          2397.0
76            325        0.64         147.0          2390.0
77            307        0.63         119.0                
78            403        0.52          83.0          2310.0
79            365        0.54          86.0          2377.0
80            386        0.52         119.0          2444.0
81            397        0.49         146.0          2368.0
82            402        0.46         101.0          2354.0
83            315        0.64         107.0          2346.0
84            312        0.57         138.0          2336.0
85            342         0.6         141.0          2377.0
86            385         0.5          68.0          2334.0
87            324        0.65         118.0          2424.0
88            405        0.54         107.0          2321.0
89            323        0.56         102.0          2367.0
90            367        0.55         117.0          2464.0
91            365        0.49          86.0          2372.0
92            370        0.47         111.0          2380.0
93            402         0.5         102.0          2362.0
94            385        0.53         135.0          2351.0
95            327        0.63         124.0          2334.0
96            295        0.59         117.0          2349.0
97            356        0.64         122.0          2440.0
98            375        0.46         137.0          2387.0
99            332        0.62          81.0          2414.0
100           377        0.55         109.0          2346.0
    absorção_agregado_pct
1                     2.3
2                    1.85
3                    1.89
4                    1.97
5                    2.31
6                     0.8
7                    1.18
8                    1.33
9                    2.92
10                   1.94
11                   1.01
12                   1.96
13                   1.79
14                   1.19
15                   1.93
16                   1.53
17                    1.4
18                   1.62
19                   0.89
20                   1.66
21                   1.36
22                   1.92
23                   1.83
24                   1.94
25                   2.54
26                   1.99
27                    2.1
28                   2.13
29                   2.09
30                   1.93
31                   1.75
32                   2.13
33                   2.06
34                   0.91
35                   2.03
36                   2.39
37                   2.41
38                   2.12
39                   2.57
40                   2.08
41                   2.33
42                   1.34
43                   1.31
44                   2.62
45                   2.12
46                   1.42
47                   2.02
48                   2.35
49                   1.48
50                   1.99
51                   0.94
52                   1.47
53                   1.79
54                   1.11
55                    1.8
56                   2.31
57                   1.02
58                   1.76
59                    1.1
60                   1.83
61                    2.1
62                   2.01
63                    1.6
64                   1.26
65                   1.18
66                   2.12
67                   1.56
68                   1.27
69                   1.71
70                   1.66
71                   1.35
72                   18.4
73                   2.06
74                   1.73
75                    2.2
76                   1.69
77                   1.38
78                    1.5
79                   2.14
80                   2.38
81                   1.74
82                    1.8
83                   1.97
84                   1.41
85                   1.86
86                   1.48
87                   2.17
88                   2.13
89                   2.24
90                   1.87
91                   0.82
92                   2.38
93                   1.57
94                   2.47
95                   1.55
96                   1.72
97                       
98                   2.04
99                   1.88
100                  1.13</code></pre>
</div>
</div>
<p>Para obter o valor de observações e de variáveis existentes no banco de dados, é possível utilizar a função <code>str()</code> e, para um resumo dessas variáveis, utiliza-se <code>summary()</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  10 variables:
 $ id_corpo_prova       : chr  "CP-001" "CP-002" "CP-003" "CP-004" ...
 $ obra                 : chr  "Bloco A" "Bloco A" "Bloco C" "Bloco A" ...
 $ tipo_concreto        : chr  "C35" "C30" "C30" "C40" ...
 $ idade_dias           : int  28 7 56 28 28 28 56 28 14 7 ...
 $ resistencia_mpa      : chr  "36.3" "28.4" "36.1" "47.2" ...
 $ cimento_kg_m3        : chr  "395" "340" "338" "407" ...
 $ relacao_a_c          : chr  "0.5" "0.54" "0.56" "0.47" ...
 $ abatimento_mm        : chr  "111.0" "114.0" "106.0" "142.0" ...
 $ densidade_kg_m3      : chr  "2332.0" "2389.0" "2427.0" "2345.0" ...
 $ absorção_agregado_pct: chr  "2.3" "1.85" "1.89" "1.97" ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova        obra       tipo_concreto   idade_dias 
 Length   :100    Length   :100   Length   :100   Min.   :  7  
 N.unique :100    N.unique :  5   N.unique :  5   1st Qu.: 14  
 N.blank  :  0    N.blank  :  0   N.blank  :  0   Median : 28  
 Min.nchar:  6    Min.nchar:  7   Min.nchar:  3   Mean   : 28  
 Max.nchar:  6    Max.nchar:  8   Max.nchar:  3   3rd Qu.: 28  
                                                  Max.   :280  
  resistencia_mpa   cimento_kg_m3    relacao_a_c    abatimento_mm
 Length   :100    Length   :100   Length   :100   Length   :100  
 N.unique : 84    N.unique : 68   N.unique : 25   N.unique : 57  
 N.blank  :  1    N.blank  :  0   N.blank  :  1   N.blank  :  1  
 Min.nchar:  0    Min.nchar:  3   Min.nchar:  0   Min.nchar:  0  
 Max.nchar:  4    Max.nchar:  4   Max.nchar:  4   Max.nchar:  6  
                                                                 
  densidade_kg_m3 absorção_agregado_pct
 Length   :100    Length   :100        
 N.unique : 65    N.unique : 82        
 N.blank  :  1    N.blank  :  1        
 Min.nchar:  0    Min.nchar:  0        
 Max.nchar:  6    Max.nchar:  4        
                                       </code></pre>
</div>
</div>
<p>Portanto, essa base de dados possui 100 observações e 10 variáveis.</p>
<p>Além do número de observações e de váriáveis, a função <code>str()</code> também apresenta qual é a classe do objeto em questão, neste caso, <code>data.frame</code>, e a estrutura de cada variável.</p>
<p>As variáveis podem ser classificadas como qualitativas ou quantitativas. As variáveis qualitativas representam características ou categorias, enquanto as quantitativas são expressas por valores numéricos e representam quantidades ou medidas.</p>
<p>Na base analisada, a identificação do corpo de prova, a obra e o tipo de concreto são variáveis qualitativas, enquanto a idade do corpo de prova, a resistência, o consumo de cimento, a relação água/cimento, o abatimento, a densidade e a absorção são variáveis quantitativas. Entretanto, dentre as variáveis quantitativas, apenas a idade do corpo de prova foi reconhecida pelo R como numérica. As demais foram reconhecidas como caracteres (<code>chr</code>), o que pode indicar a presença de inconsistências que alteraram a forma como o R interpretou essas variáveis.</p>
<p>A função <code>summary()</code> apresenta um resumo das principais características das variáveis de uma base de dados. Para variáveis numéricas, mostra medidas como mínimo, máximo, média, mediana e quartis e, para variáveis de texto, apresenta informações relacionadas à sua estrutura e conteúdo.</p>
</section>
<section id="investigação-e-limpeza-dos-dados" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="investigação-e-limpeza-dos-dados"><span class="header-section-number">4.2</span> Investigação e Limpeza dos Dados</h3>
<section id="dados-ausentes" class="level4" data-number="4.2.1">
<h4 data-number="4.2.1" class="anchored" data-anchor-id="dados-ausentes"><span class="header-section-number">4.2.1</span> Dados ausentes</h4>
<p>O próximo passo é verificar a existência de valores ausentes na base de dados e, para isso, serão realizadas as seguintes etapas:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantificar o total de valores ausentes</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(dados <span class="sc">==</span> <span class="st">""</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantificar os valores ausentes por variável</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(dados <span class="sc">==</span> <span class="st">""</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       id_corpo_prova                  obra         tipo_concreto 
                    0                     0                     0 
           idade_dias       resistencia_mpa         cimento_kg_m3 
                    0                     1                     0 
          relacao_a_c         abatimento_mm       densidade_kg_m3 
                    1                     1                     1 
absorção_agregado_pct 
                    1 </code></pre>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Localizar os valores ausentes</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ausentes <span class="ot">&lt;-</span> <span class="fu">which</span>(dados <span class="sc">==</span> <span class="st">""</span>, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar o corpo de prova e a variável correspondente</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>resultado_ausentes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">CP =</span> dados<span class="sc">$</span>id_corpo_prova[ausentes[, <span class="dv">1</span>]],</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">colnames</span>(dados)[ausentes[, <span class="dv">2</span>]]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      CP              Variavel
1 CP-092       resistencia_mpa
2 CP-038           relacao_a_c
3 CP-015         abatimento_mm
4 CP-077       densidade_kg_m3
5 CP-097 absorção_agregado_pct</code></pre>
</div>
</div>
<p>Considerando a baixa ocorrência de dados ausentes em relação ao número total de observações da base, optou-se pela exclusão das linhas que apresentaram-se como vazios. Essa abordagem permite trabalhar com observações completas nas análises subsequentes, sem a necessidade de estimar ou imputar valores não observados. Dessa forma, busca-se preservar a representatividade dos dados efetivamente disponíveis e garantir maior consistência na aplicação das análises estatísticas. A remoção dessas linhas que contém vazios será feita após as análises das Variáveis Quantitativas e Qualitativas.</p>
</section>
<section id="variáveis-quantitativas" class="level4" data-number="4.2.2">
<h4 data-number="4.2.2" class="anchored" data-anchor-id="variáveis-quantitativas"><span class="header-section-number">4.2.2</span> Variáveis quantitativas</h4>
<p>Para verificar e corrigir os dados que apresentam inconsistências dentro das variáveis quantitativas e que causaram o reconhecimento delas como <code>(chr)</code>, iremos utilizar a função <code>as.numeric()</code> para tentar converter todos os valores para números em uma cópia da base de dados, nomeada como <code>dados_conversao</code>. Já para o armazenamento dos dados tratados, será atribuído uma cópia da base de dados para <code>dados_limpos</code>, importante para manter a integridade dos dados originalmente recebidos, possibilitando a rastreabilidade das alterações realizadas e a comparação entre os dados antes e após o tratamento.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupando as variáveis com erro de tipagem</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "resistencia_mpa"       "cimento_kg_m3"         "relacao_a_c"          
[4] "abatimento_mm"         "densidade_kg_m3"       "absorção_agregado_pct"</code></pre>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Copia da base de dados para conversão e tratamento dos dados problemáticos`</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>dados_conversao <span class="ot">&lt;-</span> dados_limpos <span class="ot">&lt;-</span> dados</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertendo valores para números </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dados_conversao[variaveis_quantitativas] <span class="ot">&lt;-</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(dados[variaveis_quantitativas], as.numeric)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Após a tentativa de conversão das variáveis para o tipo numérico, observou-se que os valores que não puderam ser convertidos adequadamente foram transformados em NA pelo R. Assim, para identificar o corpo de prova e os valores problemáticos por variável, foi desenvolvido os seguintes comandos:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificando quais valores foram transformados em NA </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>problemas <span class="ot">&lt;-</span> <span class="fu">is.na</span>(dados_conversao[variaveis_quantitativas]) <span class="sc">&amp;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>             dados[variaveis_quantitativas] <span class="sc">!=</span> <span class="st">""</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Localizando as posições em que as conversões apresentaram problemas </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(problemas, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>posicoes <span class="ot">&lt;-</span> <span class="fu">which</span>(problemas, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>resultado_problemas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">CP =</span> dados<span class="sc">$</span>id_corpo_prova[posicoes[, <span class="dv">1</span>]],</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">colnames</span>(problemas)[posicoes[, <span class="dv">2</span>]],</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> dados[variaveis_quantitativas][problemas]</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     row col
[1,]   8   1
[2,]  19   1
[3,]  64   2
[4,]  45   3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      CP        Variavel Valor
1 CP-008 resistencia_mpa  38,7
2 CP-019 resistencia_mpa  3O,4
3 CP-064   cimento_kg_m3  390O
4 CP-045     relacao_a_c  0,55</code></pre>
</div>
</div>
<p>Diante disso, podemos observar que provavelmente houve erro de digitação nos 4 valores apresentados acima, como a utilização de vírgula ao invés de ponto e o uso de caractere letra junto a caractere número. Nesse segundo caso, para a variável <code>resistencia_mpa</code>o erro foi a troca da letra “o” pelo numeral zero, sendo o valor correto “30.4”, já para a variável <code>cimento_kg_m3</code>, a troca não faria sentido em termos de coerência estatística, sendo necessário a exclusão da letra “o”, assim o valor correto é “390”. Logo, para a correção desse valores, iremos realizar as devidas substituíções e exclusões no <code>dados_limpos</code>.</p>
<p>Para a correção da utilização da vírgula no lugar de ponto, utilizaremos a função <code>gsub()</code>, que procura um texto e substitui por outro, junto das funções <code>function(x)</code>, que cria uma função temporária para que x percorra cada coluna para <code>lapply()</code>analisar.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Substituindo vírgula por ponto</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  dados_limpos[variaveis_quantitativas],</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, x)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Já para a correção da letra “o” cada caso foi corrigido isoladamente.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Substituindo a letra "o" pelo algarismo zero</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>resistencia_mpa[</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>id_corpo_prova <span class="sc">==</span> <span class="st">"CP-019"</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="st">"30.4"</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluíndo a letra "o"</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>cimento_kg_m3[</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>id_corpo_prova <span class="sc">==</span> <span class="st">"CP-064"</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="st">"390"</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="er">)</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Agora, basta alterar todos esses valores corrigidos para números, utilizando <code>as.numeric()</code> e conferir a atualização dos dados com <code>str()</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  dados_limpos[variaveis_quantitativas],</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  as.numeric</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  10 variables:
 $ id_corpo_prova       : chr  "CP-001" "CP-002" "CP-003" "CP-004" ...
 $ obra                 : chr  "Bloco A" "Bloco A" "Bloco C" "Bloco A" ...
 $ tipo_concreto        : chr  "C35" "C30" "C30" "C40" ...
 $ idade_dias           : int  28 7 56 28 28 28 56 28 14 7 ...
 $ resistencia_mpa      : num  36.3 28.4 36.1 47.2 27.9 41.5 23.7 38.7 30.3 25.3 ...
 $ cimento_kg_m3        : num  395 340 338 407 316 398 351 347 346 315 ...
 $ relacao_a_c          : num  0.5 0.54 0.56 0.47 0.61 0.43 0.65 0.54 0.54 0.6 ...
 $ abatimento_mm        : num  111 114 106 142 133 98 99 116 125 127 ...
 $ densidade_kg_m3      : num  2332 2389 2427 2345 2448 ...
 $ absorção_agregado_pct: num  2.3 1.85 1.89 1.97 2.31 0.8 1.18 1.33 2.92 1.94 ...</code></pre>
</div>
</div>
<p>Ainda observando o banco de dados, agora será verificado se os dados apresentados como variáveis quantitativas são compatíveis estatisticamente. Inicialmente iremos incluir a variável <code>idade_dias</code> na atribuição <code>variaveis_quantitativas</code>, em seguida utilizar a função <code>summary()</code>, para uma visão resumida dos dados estatístico de cada variável.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inclução da variável de idade do corpo de prova e print do resumo estátistico das variáveis quantitativas</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"idade_dias"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(dados_limpos[variaveis_quantitativas], as.numeric)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_limpos[variaveis_quantitativas])</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   idade_dias  resistencia_mpa cimento_kg_m3    relacao_a_c    
 Min.   :  7   Min.   :19.00   Min.   :295.0   Min.   :0.4300  
 1st Qu.: 14   1st Qu.:28.75   1st Qu.:339.5   1st Qu.:0.5100  
 Median : 28   Median :32.30   Median :354.0   Median :0.5600  
 Mean   : 28   Mean   :33.55   Mean   :357.6   Mean   :0.5537  
 3rd Qu.: 28   3rd Qu.:38.35   3rd Qu.:385.0   3rd Qu.:0.6000  
 Max.   :280   Max.   :47.50   Max.   :418.0   Max.   :0.6500  
               NAs    :1                       NAs    :1       
 abatimento_mm    densidade_kg_m3 absorção_agregado_pct
 Min.   :  64.0   Min.   : 238    Min.   : 0.800       
 1st Qu.:  99.5   1st Qu.:2348    1st Qu.: 1.475       
 Median : 110.0   Median :2374    Median : 1.850       
 Mean   : 121.7   Mean   :2351    Mean   : 1.953       
 3rd Qu.: 122.5   3rd Qu.:2388    3rd Qu.: 2.110       
 Max.   :1250.0   Max.   :2464    Max.   :18.400       
 NAs    :1        NAs    :1       NAs    :1            </code></pre>
</div>
</div>
<p>A partir dessa visualização, ao comparar as medidas de tendência central com os valores mínimos e máximos das variáveis, observa-se a presença de alguns valores que destoam significativamente do comportamento geral dos dados, indicando possíveis erros de digitação. A idade dos corpos de prova apresenta média de 28 dias, enquanto o valor máximo registrado é de 280 dias. Para o abatimento do concreto, verifica-se média de 121,70 mm e valor máximo de 1.250,00 mm. Em relação à densidade, a média observada é de 2,351 kg/m³, enquanto o valor mínimo corresponde a apenas 238 kg/m³. Por fim, a absorção de água do agregado apresenta média de 1,95%, contrastando com o valor máximo de 18,40%. A seguir, iremos localizar as amostras correspondente a esses dados e realizar os devidos refinamentos com base nos resultados esperados para as variáveis estudadas.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>idade_dias[</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>idade_dias <span class="sc">==</span> <span class="dv">280</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">28</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>abatimento_mm[</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>abatimento_mm <span class="sc">==</span> <span class="dv">1250</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">125</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>densidade_kg_m3[</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>densidade_kg_m3 <span class="sc">==</span> <span class="dv">238</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">2380</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>absorção_agregado_pct[</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>absorção_agregado_pct <span class="sc">==</span> <span class="fl">18.4</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="fl">1.84</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="variáveis-qualitativas" class="level4" data-number="4.2.3">
<h4 data-number="4.2.3" class="anchored" data-anchor-id="variáveis-qualitativas"><span class="header-section-number">4.2.3</span> Variáveis qualitativas</h4>
<p>Concluído os ajustes das variáveis quantitativas, vamos agora analisar as variáveis qualitativas, de <code>obra</code>e <code>tipo_concreto</code>. Para isso utilizaremos a função <code>unique()</code>, a seguir.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação de valores diferentes dentro de cada variável</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>obra)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>tipo_concreto)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bloco A"  "Bloco C"  "Bloco B"  "Bloco D"  "Bloco B "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C35" "C30" "C40" "C25" "c30"</code></pre>
</div>
</div>
<p>Para a variável <code>obra</code>, observa-se que as amostras foram coletadas em quatro blocos, identificados como A, B, C e D. Entretanto, foi identificada uma inconsistência na padronização dos dados referentes ao Bloco B, em que alguns registros apresentam um caractere de espaço adicional ao final do texto. Já para a variável <code>tipo_concreto</code>, observa-se que as classes de concreto são identificadas pelo padrão de escrita com a letra C maiúscula, seguida do respectivo valor numérico. Entretanto, foi identificado que há registros da classe C30 digitado como “c30”, com letra minúscula. Essas diferenças faz com que o R interprete os registros como categorias distintas, podendo comprometer o agrupamento das observações e, consequentemente, a obtenção e interpretação dos resultados. Sendo assim, foi feito os devidos ajustes para que as mesma categorias possam ser agrupadas.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remoção de espaços em `obra`</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>obra <span class="ot">&lt;-</span> <span class="fu">trimws</span>(dados_limpos<span class="sc">$</span>obra)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Alteração para letras maiúsculas em `tipo_concreto`</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>tipo_concreto <span class="ot">&lt;-</span> <span class="fu">toupper</span>(dados_limpos<span class="sc">$</span>tipo_concreto)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bloco A" "Bloco C" "Bloco B" "Bloco D"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C35" "C30" "C40" "C25"</code></pre>
</div>
</div>
<p>Por fim, será feita a remoção das linhas em que há falta de preenchimento de dados, itentificados pelos corpos de prova CP-092, CP-038, CP-015, CP-077 e CP-097, no item 4.2.1 Dados Ausentes.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>dados_limpos <span class="ot">&lt;-</span> <span class="fu">subset</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  dados_limpos,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">!</span>(id_corpo_prova <span class="sc">%in%</span> <span class="fu">c</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-092"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-038"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-015"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-077"</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-097"</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Após a identificação e o tratamento das inconsistências presentes na base de dados, realizou-se uma nova verificação do conjunto de dados <code>dados_limpos</code>, com o objetivo de avaliar a estrutura das variáveis e conferir os resultados obtidos após o processo de limpeza.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados_limpos)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_limpos)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   95 obs. of  10 variables:
 $ id_corpo_prova       : chr  "CP-001" "CP-002" "CP-003" "CP-004" ...
 $ obra                 : chr  "Bloco A" "Bloco A" "Bloco C" "Bloco A" ...
 $ tipo_concreto        : chr  "C35" "C30" "C30" "C40" ...
 $ idade_dias           : num  28 7 56 28 28 28 56 28 14 7 ...
 $ resistencia_mpa      : num  36.3 28.4 36.1 47.2 27.9 41.5 23.7 38.7 30.3 25.3 ...
 $ cimento_kg_m3        : num  395 340 338 407 316 398 351 347 346 315 ...
 $ relacao_a_c          : num  0.5 0.54 0.56 0.47 0.61 0.43 0.65 0.54 0.54 0.6 ...
 $ abatimento_mm        : num  111 114 106 142 133 98 99 116 125 127 ...
 $ densidade_kg_m3      : num  2332 2389 2427 2345 2448 ...
 $ absorção_agregado_pct: num  2.3 1.85 1.89 1.97 2.31 0.8 1.18 1.33 2.92 1.94 ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova        obra      tipo_concreto   idade_dias   
 Length   :95     Length   :95   Length   :95    Min.   : 7.00  
 N.unique :95     N.unique : 4   N.unique : 4    1st Qu.:14.00  
 N.blank  : 0     N.blank  : 0   N.blank  : 0    Median :28.00  
 Min.nchar: 6     Min.nchar: 7   Min.nchar: 3    Mean   :25.79  
 Max.nchar: 6     Max.nchar: 7   Max.nchar: 3    3rd Qu.:28.00  
                                                 Max.   :56.00  
 resistencia_mpa cimento_kg_m3    relacao_a_c     abatimento_mm  
 Min.   :21.30   Min.   :295.0   Min.   :0.4300   Min.   : 64.0  
 1st Qu.:29.30   1st Qu.:340.0   1st Qu.:0.5100   1st Qu.: 99.0  
 Median :32.70   Median :353.0   Median :0.5600   Median :109.0  
 Mean   :33.83   Mean   :358.5   Mean   :0.5536   Mean   :109.7  
 3rd Qu.:38.55   3rd Qu.:385.0   3rd Qu.:0.5950   3rd Qu.:122.5  
 Max.   :47.50   Max.   :418.0   Max.   :0.6500   Max.   :175.0  
 densidade_kg_m3 absorção_agregado_pct
 Min.   :2293    Min.   :0.800        
 1st Qu.:2348    1st Qu.:1.475        
 Median :2374    Median :1.830        
 Mean   :2373    Mean   :1.779        
 3rd Qu.:2388    3rd Qu.:2.095        
 Max.   :2464    Max.   :2.920        </code></pre>
</div>
</div>
<p>A partir da aplicação da função <code>str()</code>, verificou-se que a base de dados tratada agora é composta por 95 observações e 10 variáveis. Após o processo de limpeza, as variáveis quantitativas foram adequadamente convertidas para o tipo numérico (num), enquanto as variáveis qualitativas permaneceram armazenadas como caracteres (chr).</p>
<p>Por meio da função <code>summary()</code>, foi possível verificar o comportamento das variáveis após as correções realizadas. Observa-se que os valores anteriormente identificados como discrepantes foram tratados, resultando em intervalos mais coerentes para as variáveis analisadas. A idade dos corpos de prova passou a variar entre 7 e 56 dias, o abatimento entre 64 e 175 mm, a densidade entre 2.293 e 2.464 kg/m³ e a absorção de água do agregado entre 0,80% e 2,92%.</p>
<p>Além disso, as variáveis resistência à compressão, consumo de cimento e relação água/cimento apresentaram valores entre 19,0 e 47,5 MPa, 295 e 418 kg/m³ e 0,43 e 0,65, respectivamente. Dessa forma, a nova inspeção indica que as inconsistências identificadas nas etapas anteriores foram corrigidas, tornando a base mais adequada para as análises subsequentes.</p>
</section>
</section>
<section id="exploração-dos-dados" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="exploração-dos-dados"><span class="header-section-number">4.3</span> Exploração dos dados</h3>
<p>Após o tratamento da base de dados, procedeu-se à análise estatística descritiva da resistência à compressão dos corpos de prova.</p>
<p>Para a resistência média geral foi utilizado a função <code>mean()</code></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>media_resistencia <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_limpos<span class="sc">$</span>resistencia_mpa)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.82632</code></pre>
</div>
</div>
</section>
</section>
<section id="considerações-finais" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="considerações-finais"><span class="header-section-number">5</span> 🧠 Considerações finais</h2>
<p>Apresente uma síntese dos principais pontos observados no experimento.</p>
<ul>
<li>Retome o objetivo da prática e indique se ele foi alcançado.</li>
<li>Destaque os principais aprendizados obtidos.</li>
<li>Comente brevemente sobre a qualidade dos dados coletados.</li>
<li>Sugira possíveis melhorias no procedimento experimental.</li>
</ul>
<p>Evite repetir apenas os resultados; foque nas <strong>conclusões e reflexões</strong> sobre a `variaveis prática realizada.</p>
</section>
<section id="referências" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referências"><span class="header-section-number">6</span> 📖 Referências</h2>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Só mude aqui!!!!</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Maria Clara Figueiredo Coelho e Victória Raspante Marques"</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Relatório de Aula Prática 02"</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> referencias.bib</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># A partir daqui nao faca alteracoes!!!!!</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="an">link-citations:</span><span class="co"> true</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> associacao-brasileira-de-normas-tecnicas-ipea.csl</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "&lt;a href='https://bendeivide.github.io/courses/epaec/' target='_blank'&gt;Estatística e Probabilidade&lt;/a&gt; &lt;/br&gt; &lt;a href='https://bendeivide.github.io' target='_blank'&gt;Prof. Ben Dêivide (DEFIM/CAP/UFSJ)&lt;/a&gt;"</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="an">include-before-body:</span><span class="co"> header.html</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> now</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="an">date-format:</span><span class="co"> "DD/MM/YYYY, HH:mm"</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> pt-BR</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: bootstrap</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a><span class="co">    #css: styles.css</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📌 Introdução</span></span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a>A análise de dados é uma ferramenta de grande valor para o acompanhamento e o controle de qualidade dos materiais empregados nas obras, no âmbito da Engenharia Civil. No controle tecnológico do concreto, informações como resistência à compressão, abatimento, relação água/cimento e idade dos corpos de prova auxiliam na avaliação do desempenho do material e na identificação de possíveis resultados fora do comportamento esperado.</span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a>Entretanto, dados obtidos em ensaios, registros de campo e planilhas podem apresentar valores ausentes, erros de digitação e inconsistências de preenchimento. Por esse motivo, antes da realização das análises estatísticas, é importante verificar a qualidade dos registros e realizar os tratamentos necessários para garantir maior confiabilidade aos resultados.</span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a>Nesse contexto, este relatório utilizará a linguagem R para inspecionar, tratar e explorar uma base de dados relacionada ao controle tecnológico do concreto, buscando transformar os dados brutos em informações úteis para sua análise e interpretação.</span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🎯 Objetivos</span></span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivo geral</span></span>
<span id="cb39-41"><a href="#cb39-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-42"><a href="#cb39-42" aria-hidden="true" tabindex="-1"></a>Processar e analisar uma base de dados referente ao controle tecnológico do concreto, utilizando a linguagem R para identificar e tratar inconsistências e obter informações relevantes para a interpretação dos resultados.</span>
<span id="cb39-43"><a href="#cb39-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-44"><a href="#cb39-44" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivos específicos</span></span>
<span id="cb39-45"><a href="#cb39-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-46"><a href="#cb39-46" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Inspecionar a estrutura e as características da base de dados;</span>
<span id="cb39-47"><a href="#cb39-47" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Identificar valores ausentes, erros de digitação e possíveis inconsistências;</span>
<span id="cb39-48"><a href="#cb39-48" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Padronizar e tratar as variáveis para realização das análises;</span>
<span id="cb39-49"><a href="#cb39-49" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Aplicar recursos da linguagem R para manipulação e exploração dos dados;</span>
<span id="cb39-50"><a href="#cb39-50" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Calcular e comparar resultados relacionados às propriedades do concreto;</span>
<span id="cb39-51"><a href="#cb39-51" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Investigar relações entre variáveis relevantes para o controle tecnológico;</span>
<span id="cb39-52"><a href="#cb39-52" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Interpretar os resultados obtidos considerando sua aplicação na Engenharia Civil.</span>
<span id="cb39-53"><a href="#cb39-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-54"><a href="#cb39-54" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb39-55"><a href="#cb39-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-56"><a href="#cb39-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## ⚙️ Metodologia</span></span>
<span id="cb39-57"><a href="#cb39-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-58"><a href="#cb39-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-59"><a href="#cb39-59" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb39-60"><a href="#cb39-60" aria-hidden="true" tabindex="-1"></a>Descreva como o experimento foi realizado.</span>
<span id="cb39-61"><a href="#cb39-61" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb39-62"><a href="#cb39-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-63"><a href="#cb39-63" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Materiais utilizados  </span>
<span id="cb39-64"><a href="#cb39-64" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Procedimento  </span>
<span id="cb39-65"><a href="#cb39-65" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Número de repetições  </span>
<span id="cb39-66"><a href="#cb39-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-67"><a href="#cb39-67" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb39-68"><a href="#cb39-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-69"><a href="#cb39-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🔍 Resultados e Discussão</span></span>
<span id="cb39-70"><a href="#cb39-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-71"><a href="#cb39-71" aria-hidden="true" tabindex="-1"></a><span class="fu">### Importação do banco de dados</span></span>
<span id="cb39-72"><a href="#cb39-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-73"><a href="#cb39-73" aria-hidden="true" tabindex="-1"></a>A base de dados foi importada para o R através da função <span class="in">`read.csv2()`</span> e atribuída a <span class="in">`dados`</span>:</span>
<span id="cb39-74"><a href="#cb39-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-75"><a href="#cb39-75" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-76"><a href="#cb39-76" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(</span>
<span id="cb39-77"><a href="#cb39-77" aria-hidden="true" tabindex="-1"></a>  <span class="st">"base_processamento_dados_engenharia_civil.csv"</span>,</span>
<span id="cb39-78"><a href="#cb39-78" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-79"><a href="#cb39-79" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb39-80"><a href="#cb39-80" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-81"><a href="#cb39-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-82"><a href="#cb39-82" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-83"><a href="#cb39-83" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(</span>
<span id="cb39-84"><a href="#cb39-84" aria-hidden="true" tabindex="-1"></a>  <span class="st">"base_processamento_dados_engenharia_civil.csv"</span>,</span>
<span id="cb39-85"><a href="#cb39-85" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-86"><a href="#cb39-86" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb39-87"><a href="#cb39-87" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-88"><a href="#cb39-88" aria-hidden="true" tabindex="-1"></a>dados</span>
<span id="cb39-89"><a href="#cb39-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-90"><a href="#cb39-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-91"><a href="#cb39-91" aria-hidden="true" tabindex="-1"></a>Para obter o valor de observações e de variáveis existentes no banco de dados, é possível utilizar a função <span class="in">`str()`</span> e, para um resumo dessas variáveis, utiliza-se <span class="in">`summary()`</span>:</span>
<span id="cb39-92"><a href="#cb39-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-93"><a href="#cb39-93" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-94"><a href="#cb39-94" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados)</span>
<span id="cb39-95"><a href="#cb39-95" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span>
<span id="cb39-96"><a href="#cb39-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-97"><a href="#cb39-97" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-98"><a href="#cb39-98" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados)</span>
<span id="cb39-99"><a href="#cb39-99" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span>
<span id="cb39-100"><a href="#cb39-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-101"><a href="#cb39-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-102"><a href="#cb39-102" aria-hidden="true" tabindex="-1"></a>Portanto, essa base de dados possui 100 observações e 10 variáveis.</span>
<span id="cb39-103"><a href="#cb39-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-104"><a href="#cb39-104" aria-hidden="true" tabindex="-1"></a>Além do número de observações e de váriáveis, a função <span class="in">`str()`</span> também apresenta qual é a classe do objeto em questão, neste caso, <span class="in">`data.frame`</span>, e a estrutura de cada variável.</span>
<span id="cb39-105"><a href="#cb39-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-106"><a href="#cb39-106" aria-hidden="true" tabindex="-1"></a>As variáveis podem ser classificadas como qualitativas ou quantitativas. As variáveis qualitativas representam características ou categorias, enquanto as quantitativas são expressas por valores numéricos e representam quantidades ou medidas.</span>
<span id="cb39-107"><a href="#cb39-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-108"><a href="#cb39-108" aria-hidden="true" tabindex="-1"></a>Na base analisada, a identificação do corpo de prova, a obra e o tipo de concreto são variáveis qualitativas, enquanto a idade do corpo de prova, a resistência, o consumo de cimento, a relação água/cimento, o abatimento, a densidade e a absorção são variáveis quantitativas. Entretanto, dentre as variáveis quantitativas, apenas a idade do corpo de prova foi reconhecida pelo R como numérica. As demais foram reconhecidas como caracteres (<span class="in">`chr`</span>), o que pode indicar a presença de inconsistências que alteraram a forma como o R interpretou essas variáveis.</span>
<span id="cb39-109"><a href="#cb39-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-110"><a href="#cb39-110" aria-hidden="true" tabindex="-1"></a>A função <span class="in">`summary()`</span> apresenta um resumo das principais características das variáveis de uma base de dados. Para variáveis numéricas, mostra medidas como mínimo, máximo, média, mediana e quartis e, para variáveis de texto, apresenta informações relacionadas à sua estrutura e conteúdo.</span>
<span id="cb39-111"><a href="#cb39-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-112"><a href="#cb39-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### Investigação e Limpeza dos Dados</span></span>
<span id="cb39-113"><a href="#cb39-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-114"><a href="#cb39-114" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Dados ausentes</span></span>
<span id="cb39-115"><a href="#cb39-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-116"><a href="#cb39-116" aria-hidden="true" tabindex="-1"></a>O próximo passo é verificar a existência de valores ausentes na base de dados e, para isso, serão realizadas as seguintes etapas:</span>
<span id="cb39-117"><a href="#cb39-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-118"><a href="#cb39-118" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-119"><a href="#cb39-119" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantificar o total de valores ausentes</span></span>
<span id="cb39-120"><a href="#cb39-120" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(dados <span class="sc">==</span> <span class="st">""</span>)</span>
<span id="cb39-121"><a href="#cb39-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-122"><a href="#cb39-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-123"><a href="#cb39-123" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(dados <span class="sc">==</span> <span class="st">""</span>)</span>
<span id="cb39-124"><a href="#cb39-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-125"><a href="#cb39-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-126"><a href="#cb39-126" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-127"><a href="#cb39-127" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantificar os valores ausentes por variável</span></span>
<span id="cb39-128"><a href="#cb39-128" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(dados <span class="sc">==</span> <span class="st">""</span>)</span>
<span id="cb39-129"><a href="#cb39-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-130"><a href="#cb39-130" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-131"><a href="#cb39-131" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(dados <span class="sc">==</span> <span class="st">""</span>)</span>
<span id="cb39-132"><a href="#cb39-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-133"><a href="#cb39-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-134"><a href="#cb39-134" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-135"><a href="#cb39-135" aria-hidden="true" tabindex="-1"></a><span class="co"># Localizar os valores ausentes</span></span>
<span id="cb39-136"><a href="#cb39-136" aria-hidden="true" tabindex="-1"></a>ausentes <span class="ot">&lt;-</span> <span class="fu">which</span>(dados <span class="sc">==</span> <span class="st">""</span>, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-137"><a href="#cb39-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-138"><a href="#cb39-138" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar o corpo de prova e a variável correspondente</span></span>
<span id="cb39-139"><a href="#cb39-139" aria-hidden="true" tabindex="-1"></a>resultado_ausentes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-140"><a href="#cb39-140" aria-hidden="true" tabindex="-1"></a>  <span class="at">CP =</span> dados<span class="sc">$</span>id_corpo_prova[ausentes[, <span class="dv">1</span>]],</span>
<span id="cb39-141"><a href="#cb39-141" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">colnames</span>(dados)[ausentes[, <span class="dv">2</span>]]</span>
<span id="cb39-142"><a href="#cb39-142" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-143"><a href="#cb39-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-144"><a href="#cb39-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-145"><a href="#cb39-145" aria-hidden="true" tabindex="-1"></a>ausentes <span class="ot">&lt;-</span> <span class="fu">which</span>(dados <span class="sc">==</span> <span class="st">""</span>, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-146"><a href="#cb39-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-147"><a href="#cb39-147" aria-hidden="true" tabindex="-1"></a>resultado_ausentes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-148"><a href="#cb39-148" aria-hidden="true" tabindex="-1"></a>  <span class="at">CP =</span> dados<span class="sc">$</span>id_corpo_prova[ausentes[, <span class="dv">1</span>]],</span>
<span id="cb39-149"><a href="#cb39-149" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">colnames</span>(dados)[ausentes[, <span class="dv">2</span>]]</span>
<span id="cb39-150"><a href="#cb39-150" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-151"><a href="#cb39-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-152"><a href="#cb39-152" aria-hidden="true" tabindex="-1"></a>resultado_ausentes</span>
<span id="cb39-153"><a href="#cb39-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-154"><a href="#cb39-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-155"><a href="#cb39-155" aria-hidden="true" tabindex="-1"></a>Considerando a baixa ocorrência de dados ausentes em relação ao número total de observações da base, optou-se pela exclusão das linhas que apresentaram-se como vazios. Essa abordagem permite trabalhar com observações completas nas análises subsequentes, sem a necessidade de estimar ou imputar valores não observados. Dessa forma, busca-se preservar a representatividade dos dados efetivamente disponíveis e garantir maior consistência na aplicação das análises estatísticas. A remoção dessas linhas que contém vazios será feita após as análises das Variáveis Quantitativas e Qualitativas.</span>
<span id="cb39-156"><a href="#cb39-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-157"><a href="#cb39-157" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Variáveis quantitativas</span></span>
<span id="cb39-158"><a href="#cb39-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-159"><a href="#cb39-159" aria-hidden="true" tabindex="-1"></a>Para verificar e corrigir os dados que apresentam inconsistências dentro das variáveis quantitativas e que causaram o reconhecimento delas como <span class="in">`(chr)`</span>, iremos utilizar a função <span class="in">`as.numeric()`</span> para tentar converter todos os valores para números em uma cópia da base de dados, nomeada como <span class="in">`dados_conversao`</span>. Já para o armazenamento dos dados tratados, será atribuído uma cópia da base de dados para <span class="in">`dados_limpos`</span>, importante para manter a integridade dos dados originalmente recebidos, possibilitando a rastreabilidade das alterações realizadas e a comparação entre os dados antes e após o tratamento.</span>
<span id="cb39-160"><a href="#cb39-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-161"><a href="#cb39-161" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-162"><a href="#cb39-162" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupando as variáveis com erro de tipagem</span></span>
<span id="cb39-163"><a href="#cb39-163" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb39-164"><a href="#cb39-164" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb39-165"><a href="#cb39-165" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb39-166"><a href="#cb39-166" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb39-167"><a href="#cb39-167" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb39-168"><a href="#cb39-168" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb39-169"><a href="#cb39-169" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb39-170"><a href="#cb39-170" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-171"><a href="#cb39-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-172"><a href="#cb39-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-173"><a href="#cb39-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-174"><a href="#cb39-174" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb39-175"><a href="#cb39-175" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb39-176"><a href="#cb39-176" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb39-177"><a href="#cb39-177" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb39-178"><a href="#cb39-178" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb39-179"><a href="#cb39-179" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb39-180"><a href="#cb39-180" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb39-181"><a href="#cb39-181" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-182"><a href="#cb39-182" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas</span>
<span id="cb39-183"><a href="#cb39-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-184"><a href="#cb39-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-185"><a href="#cb39-185" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-186"><a href="#cb39-186" aria-hidden="true" tabindex="-1"></a><span class="co"># Copia da base de dados para conversão e tratamento dos dados problemáticos`</span></span>
<span id="cb39-187"><a href="#cb39-187" aria-hidden="true" tabindex="-1"></a>dados_conversao <span class="ot">&lt;-</span> dados_limpos <span class="ot">&lt;-</span> dados</span>
<span id="cb39-188"><a href="#cb39-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-189"><a href="#cb39-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-190"><a href="#cb39-190" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-191"><a href="#cb39-191" aria-hidden="true" tabindex="-1"></a>dados_conversao <span class="ot">&lt;-</span> dados_limpos <span class="ot">&lt;-</span> dados</span>
<span id="cb39-192"><a href="#cb39-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-193"><a href="#cb39-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-194"><a href="#cb39-194" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-195"><a href="#cb39-195" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertendo valores para números </span></span>
<span id="cb39-196"><a href="#cb39-196" aria-hidden="true" tabindex="-1"></a>dados_conversao[variaveis_quantitativas] <span class="ot">&lt;-</span></span>
<span id="cb39-197"><a href="#cb39-197" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(dados[variaveis_quantitativas], as.numeric)</span>
<span id="cb39-198"><a href="#cb39-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-199"><a href="#cb39-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-200"><a href="#cb39-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-201"><a href="#cb39-201" aria-hidden="true" tabindex="-1"></a>dados_conversao[variaveis_quantitativas] <span class="ot">&lt;-</span></span>
<span id="cb39-202"><a href="#cb39-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(dados[variaveis_quantitativas], as.numeric)</span>
<span id="cb39-203"><a href="#cb39-203" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-204"><a href="#cb39-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-205"><a href="#cb39-205" aria-hidden="true" tabindex="-1"></a>Após a tentativa de conversão das variáveis para o tipo numérico, observou-se que os valores que não puderam ser convertidos adequadamente foram transformados em NA pelo R.</span>
<span id="cb39-206"><a href="#cb39-206" aria-hidden="true" tabindex="-1"></a>Assim, para identificar o corpo de prova e os valores problemáticos por variável, foi desenvolvido os seguintes comandos:</span>
<span id="cb39-207"><a href="#cb39-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-208"><a href="#cb39-208" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-209"><a href="#cb39-209" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificando quais valores foram transformados em NA </span></span>
<span id="cb39-210"><a href="#cb39-210" aria-hidden="true" tabindex="-1"></a>problemas <span class="ot">&lt;-</span> <span class="fu">is.na</span>(dados_conversao[variaveis_quantitativas]) <span class="sc">&amp;</span></span>
<span id="cb39-211"><a href="#cb39-211" aria-hidden="true" tabindex="-1"></a>             dados[variaveis_quantitativas] <span class="sc">!=</span> <span class="st">""</span></span>
<span id="cb39-212"><a href="#cb39-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-213"><a href="#cb39-213" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-214"><a href="#cb39-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-215"><a href="#cb39-215" aria-hidden="true" tabindex="-1"></a>problemas <span class="ot">&lt;-</span> <span class="fu">is.na</span>(dados_conversao[variaveis_quantitativas]) <span class="sc">&amp;</span></span>
<span id="cb39-216"><a href="#cb39-216" aria-hidden="true" tabindex="-1"></a>             dados[variaveis_quantitativas] <span class="sc">!=</span> <span class="st">""</span></span>
<span id="cb39-217"><a href="#cb39-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-218"><a href="#cb39-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-219"><a href="#cb39-219" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-220"><a href="#cb39-220" aria-hidden="true" tabindex="-1"></a><span class="co"># Localizando as posições em que as conversões apresentaram problemas </span></span>
<span id="cb39-221"><a href="#cb39-221" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(problemas, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-222"><a href="#cb39-222" aria-hidden="true" tabindex="-1"></a>posicoes <span class="ot">&lt;-</span> <span class="fu">which</span>(problemas, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-223"><a href="#cb39-223" aria-hidden="true" tabindex="-1"></a>resultado_problemas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-224"><a href="#cb39-224" aria-hidden="true" tabindex="-1"></a>  <span class="at">CP =</span> dados<span class="sc">$</span>id_corpo_prova[posicoes[, <span class="dv">1</span>]],</span>
<span id="cb39-225"><a href="#cb39-225" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">colnames</span>(problemas)[posicoes[, <span class="dv">2</span>]],</span>
<span id="cb39-226"><a href="#cb39-226" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> dados[variaveis_quantitativas][problemas]</span>
<span id="cb39-227"><a href="#cb39-227" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-228"><a href="#cb39-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-229"><a href="#cb39-229" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-230"><a href="#cb39-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-231"><a href="#cb39-231" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(problemas, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-232"><a href="#cb39-232" aria-hidden="true" tabindex="-1"></a>posicoes <span class="ot">&lt;-</span> <span class="fu">which</span>(problemas, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-233"><a href="#cb39-233" aria-hidden="true" tabindex="-1"></a>resultado_problemas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-234"><a href="#cb39-234" aria-hidden="true" tabindex="-1"></a>  <span class="at">CP =</span> dados<span class="sc">$</span>id_corpo_prova[posicoes[, <span class="dv">1</span>]],</span>
<span id="cb39-235"><a href="#cb39-235" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variavel =</span> <span class="fu">colnames</span>(problemas)[posicoes[, <span class="dv">2</span>]],</span>
<span id="cb39-236"><a href="#cb39-236" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> dados[variaveis_quantitativas][problemas]</span>
<span id="cb39-237"><a href="#cb39-237" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-238"><a href="#cb39-238" aria-hidden="true" tabindex="-1"></a>resultado_problemas</span>
<span id="cb39-239"><a href="#cb39-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-240"><a href="#cb39-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-241"><a href="#cb39-241" aria-hidden="true" tabindex="-1"></a>Diante disso, podemos observar que provavelmente houve erro de digitação nos 4 valores apresentados acima, como a utilização de vírgula ao invés de ponto e o uso de caractere letra junto a caractere número. Nesse segundo caso, para a variável <span class="in">`resistencia_mpa`</span>o erro foi a troca da letra "o" pelo numeral zero, sendo o valor correto "30.4", já para a variável <span class="in">`cimento_kg_m3`</span>, a troca não faria sentido em termos de coerência estatística, sendo necessário a exclusão da letra "o", assim o valor correto é "390". Logo, para a correção desse valores, iremos realizar as devidas substituíções e exclusões no <span class="in">`dados_limpos`</span>.</span>
<span id="cb39-242"><a href="#cb39-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-243"><a href="#cb39-243" aria-hidden="true" tabindex="-1"></a>Para a correção da utilização da vírgula no lugar de ponto, utilizaremos a função <span class="in">`gsub()`</span>, que procura um texto e substitui por outro, junto das funções <span class="in">`function(x)`</span>, que cria uma função temporária para que x percorra cada coluna para <span class="in">`lapply()`</span>analisar.</span>
<span id="cb39-244"><a href="#cb39-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-245"><a href="#cb39-245" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-246"><a href="#cb39-246" aria-hidden="true" tabindex="-1"></a><span class="co"># Substituindo vírgula por ponto</span></span>
<span id="cb39-247"><a href="#cb39-247" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb39-248"><a href="#cb39-248" aria-hidden="true" tabindex="-1"></a>  dados_limpos[variaveis_quantitativas],</span>
<span id="cb39-249"><a href="#cb39-249" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, x)</span>
<span id="cb39-250"><a href="#cb39-250" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-251"><a href="#cb39-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-252"><a href="#cb39-252" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-253"><a href="#cb39-253" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb39-254"><a href="#cb39-254" aria-hidden="true" tabindex="-1"></a>  dados_limpos[variaveis_quantitativas],</span>
<span id="cb39-255"><a href="#cb39-255" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, x)</span>
<span id="cb39-256"><a href="#cb39-256" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-257"><a href="#cb39-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-258"><a href="#cb39-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-259"><a href="#cb39-259" aria-hidden="true" tabindex="-1"></a>Já para a correção da letra "o" cada caso foi corrigido isoladamente.</span>
<span id="cb39-260"><a href="#cb39-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-261"><a href="#cb39-261" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-262"><a href="#cb39-262" aria-hidden="true" tabindex="-1"></a><span class="co"># Substituindo a letra "o" pelo algarismo zero</span></span>
<span id="cb39-263"><a href="#cb39-263" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>resistencia_mpa[</span>
<span id="cb39-264"><a href="#cb39-264" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>id_corpo_prova <span class="sc">==</span> <span class="st">"CP-019"</span></span>
<span id="cb39-265"><a href="#cb39-265" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="st">"30.4"</span></span>
<span id="cb39-266"><a href="#cb39-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-267"><a href="#cb39-267" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluíndo a letra "o"</span></span>
<span id="cb39-268"><a href="#cb39-268" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>cimento_kg_m3[</span>
<span id="cb39-269"><a href="#cb39-269" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>id_corpo_prova <span class="sc">==</span> <span class="st">"CP-064"</span></span>
<span id="cb39-270"><a href="#cb39-270" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="st">"390"</span></span>
<span id="cb39-271"><a href="#cb39-271" aria-hidden="true" tabindex="-1"></a><span class="er">)</span></span>
<span id="cb39-272"><a href="#cb39-272" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-273"><a href="#cb39-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-274"><a href="#cb39-274" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>resistencia_mpa[</span>
<span id="cb39-275"><a href="#cb39-275" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>id_corpo_prova <span class="sc">==</span> <span class="st">"CP-019"</span></span>
<span id="cb39-276"><a href="#cb39-276" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="st">"30.4"</span></span>
<span id="cb39-277"><a href="#cb39-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-278"><a href="#cb39-278" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>cimento_kg_m3[</span>
<span id="cb39-279"><a href="#cb39-279" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>id_corpo_prova <span class="sc">==</span> <span class="st">"CP-064"</span></span>
<span id="cb39-280"><a href="#cb39-280" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="st">"390"</span></span>
<span id="cb39-281"><a href="#cb39-281" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-282"><a href="#cb39-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-283"><a href="#cb39-283" aria-hidden="true" tabindex="-1"></a>Agora, basta alterar todos esses valores corrigidos para números, utilizando <span class="in">`as.numeric()`</span> e conferir a atualização dos dados com <span class="in">`str()`</span>.</span>
<span id="cb39-284"><a href="#cb39-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-285"><a href="#cb39-285" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-286"><a href="#cb39-286" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb39-287"><a href="#cb39-287" aria-hidden="true" tabindex="-1"></a>  dados_limpos[variaveis_quantitativas],</span>
<span id="cb39-288"><a href="#cb39-288" aria-hidden="true" tabindex="-1"></a>  as.numeric</span>
<span id="cb39-289"><a href="#cb39-289" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-290"><a href="#cb39-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-291"><a href="#cb39-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-292"><a href="#cb39-292" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb39-293"><a href="#cb39-293" aria-hidden="true" tabindex="-1"></a>  dados_limpos[variaveis_quantitativas],</span>
<span id="cb39-294"><a href="#cb39-294" aria-hidden="true" tabindex="-1"></a>  as.numeric</span>
<span id="cb39-295"><a href="#cb39-295" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-296"><a href="#cb39-296" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados_limpos)</span>
<span id="cb39-297"><a href="#cb39-297" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-298"><a href="#cb39-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-299"><a href="#cb39-299" aria-hidden="true" tabindex="-1"></a>Ainda observando o banco de dados, agora será verificado se os dados apresentados como variáveis quantitativas são compatíveis estatisticamente. Inicialmente iremos incluir a variável <span class="in">`idade_dias`</span> na atribuição <span class="in">`variaveis_quantitativas`</span>, em seguida utilizar a função <span class="in">`summary()`</span>, para uma visão resumida dos dados estatístico de cada variável.</span>
<span id="cb39-300"><a href="#cb39-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-301"><a href="#cb39-301" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-302"><a href="#cb39-302" aria-hidden="true" tabindex="-1"></a><span class="co"># Inclução da variável de idade do corpo de prova e print do resumo estátistico das variáveis quantitativas</span></span>
<span id="cb39-303"><a href="#cb39-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-304"><a href="#cb39-304" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb39-305"><a href="#cb39-305" aria-hidden="true" tabindex="-1"></a>  <span class="st">"idade_dias"</span>,</span>
<span id="cb39-306"><a href="#cb39-306" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb39-307"><a href="#cb39-307" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb39-308"><a href="#cb39-308" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb39-309"><a href="#cb39-309" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb39-310"><a href="#cb39-310" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb39-311"><a href="#cb39-311" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb39-312"><a href="#cb39-312" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-313"><a href="#cb39-313" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span></span>
<span id="cb39-314"><a href="#cb39-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(dados_limpos[variaveis_quantitativas], as.numeric)</span>
<span id="cb39-315"><a href="#cb39-315" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-316"><a href="#cb39-316" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_limpos[variaveis_quantitativas])</span>
<span id="cb39-317"><a href="#cb39-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-318"><a href="#cb39-318" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-319"><a href="#cb39-319" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-320"><a href="#cb39-320" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb39-321"><a href="#cb39-321" aria-hidden="true" tabindex="-1"></a>  <span class="st">"idade_dias"</span>,</span>
<span id="cb39-322"><a href="#cb39-322" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb39-323"><a href="#cb39-323" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb39-324"><a href="#cb39-324" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb39-325"><a href="#cb39-325" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb39-326"><a href="#cb39-326" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb39-327"><a href="#cb39-327" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb39-328"><a href="#cb39-328" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-329"><a href="#cb39-329" aria-hidden="true" tabindex="-1"></a>dados_limpos[variaveis_quantitativas] <span class="ot">&lt;-</span></span>
<span id="cb39-330"><a href="#cb39-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(dados_limpos[variaveis_quantitativas], as.numeric)</span>
<span id="cb39-331"><a href="#cb39-331" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_limpos[variaveis_quantitativas])</span>
<span id="cb39-332"><a href="#cb39-332" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-333"><a href="#cb39-333" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb39-334"><a href="#cb39-334" aria-hidden="true" tabindex="-1"></a>A partir dessa visualização, ao comparar as medidas de tendência central com os valores mínimos e máximos das variáveis, observa-se a presença de alguns valores que destoam significativamente do comportamento geral dos dados, indicando possíveis erros de digitação. A idade dos corpos de prova apresenta média de 28 dias, enquanto o valor máximo registrado é de 280 dias. Para o abatimento do concreto, verifica-se média de 121,70 mm e valor máximo de 1.250,00 mm. Em relação à densidade, a média observada é de 2,351 kg/m³, enquanto o valor mínimo corresponde a apenas 238 kg/m³. Por fim, a absorção de água do agregado apresenta média de 1,95%, contrastando com o valor máximo de 18,40%. A seguir, iremos localizar as amostras correspondente a esses dados  e realizar os devidos refinamentos com base nos resultados esperados para as variáveis estudadas.</span>
<span id="cb39-335"><a href="#cb39-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-336"><a href="#cb39-336" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-337"><a href="#cb39-337" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>idade_dias[</span>
<span id="cb39-338"><a href="#cb39-338" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>idade_dias <span class="sc">==</span> <span class="dv">280</span></span>
<span id="cb39-339"><a href="#cb39-339" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">28</span></span>
<span id="cb39-340"><a href="#cb39-340" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>abatimento_mm[</span>
<span id="cb39-341"><a href="#cb39-341" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>abatimento_mm <span class="sc">==</span> <span class="dv">1250</span></span>
<span id="cb39-342"><a href="#cb39-342" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">125</span></span>
<span id="cb39-343"><a href="#cb39-343" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>densidade_kg_m3[</span>
<span id="cb39-344"><a href="#cb39-344" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>densidade_kg_m3 <span class="sc">==</span> <span class="dv">238</span></span>
<span id="cb39-345"><a href="#cb39-345" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">2380</span></span>
<span id="cb39-346"><a href="#cb39-346" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>absorção_agregado_pct[</span>
<span id="cb39-347"><a href="#cb39-347" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>absorção_agregado_pct <span class="sc">==</span> <span class="fl">18.4</span></span>
<span id="cb39-348"><a href="#cb39-348" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="fl">1.84</span></span>
<span id="cb39-349"><a href="#cb39-349" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-350"><a href="#cb39-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-351"><a href="#cb39-351" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>idade_dias[</span>
<span id="cb39-352"><a href="#cb39-352" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>idade_dias <span class="sc">==</span> <span class="dv">280</span></span>
<span id="cb39-353"><a href="#cb39-353" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">28</span></span>
<span id="cb39-354"><a href="#cb39-354" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>abatimento_mm[</span>
<span id="cb39-355"><a href="#cb39-355" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>abatimento_mm <span class="sc">==</span> <span class="dv">1250</span></span>
<span id="cb39-356"><a href="#cb39-356" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">125</span></span>
<span id="cb39-357"><a href="#cb39-357" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>densidade_kg_m3[</span>
<span id="cb39-358"><a href="#cb39-358" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>densidade_kg_m3 <span class="sc">==</span> <span class="dv">238</span></span>
<span id="cb39-359"><a href="#cb39-359" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="dv">2380</span></span>
<span id="cb39-360"><a href="#cb39-360" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>absorção_agregado_pct[</span>
<span id="cb39-361"><a href="#cb39-361" aria-hidden="true" tabindex="-1"></a>  dados_limpos<span class="sc">$</span>absorção_agregado_pct <span class="sc">==</span> <span class="fl">18.4</span></span>
<span id="cb39-362"><a href="#cb39-362" aria-hidden="true" tabindex="-1"></a>] <span class="ot">&lt;-</span> <span class="fl">1.84</span></span>
<span id="cb39-363"><a href="#cb39-363" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-364"><a href="#cb39-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-365"><a href="#cb39-365" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Variáveis qualitativas</span></span>
<span id="cb39-366"><a href="#cb39-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-367"><a href="#cb39-367" aria-hidden="true" tabindex="-1"></a>Concluído os ajustes das variáveis quantitativas, vamos agora analisar as variáveis qualitativas, de <span class="in">`obra`</span>e <span class="in">`tipo_concreto`</span>. Para isso utilizaremos a função <span class="in">`unique()`</span>, a seguir.</span>
<span id="cb39-368"><a href="#cb39-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-369"><a href="#cb39-369" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-370"><a href="#cb39-370" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação de valores diferentes dentro de cada variável</span></span>
<span id="cb39-371"><a href="#cb39-371" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>obra)</span>
<span id="cb39-372"><a href="#cb39-372" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>tipo_concreto)</span>
<span id="cb39-373"><a href="#cb39-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-374"><a href="#cb39-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-375"><a href="#cb39-375" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-376"><a href="#cb39-376" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>obra)</span>
<span id="cb39-377"><a href="#cb39-377" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>tipo_concreto)</span>
<span id="cb39-378"><a href="#cb39-378" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-379"><a href="#cb39-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-380"><a href="#cb39-380" aria-hidden="true" tabindex="-1"></a>Para a variável <span class="in">`obra`</span>, observa-se que as amostras foram coletadas em quatro blocos, identificados como A, B, C e D. Entretanto, foi identificada uma inconsistência na padronização dos dados referentes ao Bloco B, em que alguns registros apresentam um caractere de espaço adicional ao final do texto. Já para a variável <span class="in">`tipo_concreto`</span>, observa-se que as classes de concreto são identificadas pelo padrão de escrita com a letra C maiúscula, seguida do respectivo valor numérico. Entretanto, foi identificado que há registros da classe C30 digitado como "c30", com letra minúscula.</span>
<span id="cb39-381"><a href="#cb39-381" aria-hidden="true" tabindex="-1"></a>Essas diferenças faz com que o R interprete os registros como categorias distintas, podendo comprometer o agrupamento das observações e, consequentemente, a obtenção e interpretação dos resultados. Sendo assim, foi feito os devidos ajustes para que as mesma categorias possam ser agrupadas.</span>
<span id="cb39-382"><a href="#cb39-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-383"><a href="#cb39-383" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-384"><a href="#cb39-384" aria-hidden="true" tabindex="-1"></a><span class="co"># Remoção de espaços em `obra`</span></span>
<span id="cb39-385"><a href="#cb39-385" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>obra <span class="ot">&lt;-</span> <span class="fu">trimws</span>(dados_limpos<span class="sc">$</span>obra)</span>
<span id="cb39-386"><a href="#cb39-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-387"><a href="#cb39-387" aria-hidden="true" tabindex="-1"></a><span class="co"># Alteração para letras maiúsculas em `tipo_concreto`</span></span>
<span id="cb39-388"><a href="#cb39-388" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>tipo_concreto <span class="ot">&lt;-</span> <span class="fu">toupper</span>(dados_limpos<span class="sc">$</span>tipo_concreto)</span>
<span id="cb39-389"><a href="#cb39-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-390"><a href="#cb39-390" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-391"><a href="#cb39-391" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-392"><a href="#cb39-392" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>obra <span class="ot">&lt;-</span> <span class="fu">trimws</span>(dados_limpos<span class="sc">$</span>obra)</span>
<span id="cb39-393"><a href="#cb39-393" aria-hidden="true" tabindex="-1"></a>dados_limpos<span class="sc">$</span>tipo_concreto <span class="ot">&lt;-</span> <span class="fu">toupper</span>(dados_limpos<span class="sc">$</span>tipo_concreto)</span>
<span id="cb39-394"><a href="#cb39-394" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados_limpos<span class="sc">$</span>obra)</span>
<span id="cb39-395"><a href="#cb39-395" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados_limpos<span class="sc">$</span>tipo_concreto)</span>
<span id="cb39-396"><a href="#cb39-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-397"><a href="#cb39-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-398"><a href="#cb39-398" aria-hidden="true" tabindex="-1"></a>Por fim, será feita a remoção das linhas em que há falta de preenchimento de dados, itentificados pelos corpos de prova CP-092, CP-038, CP-015, CP-077 e CP-097, no item 4.2.1 Dados Ausentes.</span>
<span id="cb39-399"><a href="#cb39-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-400"><a href="#cb39-400" aria-hidden="true" tabindex="-1"></a><span class="in">```R</span></span>
<span id="cb39-401"><a href="#cb39-401" aria-hidden="true" tabindex="-1"></a>dados_limpos <span class="ot">&lt;-</span> <span class="fu">subset</span>(</span>
<span id="cb39-402"><a href="#cb39-402" aria-hidden="true" tabindex="-1"></a>  dados_limpos,</span>
<span id="cb39-403"><a href="#cb39-403" aria-hidden="true" tabindex="-1"></a>  <span class="sc">!</span>(id_corpo_prova <span class="sc">%in%</span> <span class="fu">c</span>(</span>
<span id="cb39-404"><a href="#cb39-404" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-092"</span>,</span>
<span id="cb39-405"><a href="#cb39-405" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-038"</span>,</span>
<span id="cb39-406"><a href="#cb39-406" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-015"</span>,</span>
<span id="cb39-407"><a href="#cb39-407" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-077"</span>,</span>
<span id="cb39-408"><a href="#cb39-408" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-097"</span></span>
<span id="cb39-409"><a href="#cb39-409" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb39-410"><a href="#cb39-410" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-411"><a href="#cb39-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-412"><a href="#cb39-412" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-413"><a href="#cb39-413" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-414"><a href="#cb39-414" aria-hidden="true" tabindex="-1"></a>dados_limpos <span class="ot">&lt;-</span> <span class="fu">subset</span>(</span>
<span id="cb39-415"><a href="#cb39-415" aria-hidden="true" tabindex="-1"></a>  dados_limpos,</span>
<span id="cb39-416"><a href="#cb39-416" aria-hidden="true" tabindex="-1"></a>  <span class="sc">!</span>(id_corpo_prova <span class="sc">%in%</span> <span class="fu">c</span>(</span>
<span id="cb39-417"><a href="#cb39-417" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-092"</span>,</span>
<span id="cb39-418"><a href="#cb39-418" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-038"</span>,</span>
<span id="cb39-419"><a href="#cb39-419" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-015"</span>,</span>
<span id="cb39-420"><a href="#cb39-420" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-077"</span>,</span>
<span id="cb39-421"><a href="#cb39-421" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CP-097"</span></span>
<span id="cb39-422"><a href="#cb39-422" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb39-423"><a href="#cb39-423" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-424"><a href="#cb39-424" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-425"><a href="#cb39-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-426"><a href="#cb39-426" aria-hidden="true" tabindex="-1"></a>Após a identificação e o tratamento das inconsistências presentes na base de dados, realizou-se uma nova verificação do conjunto de dados <span class="in">`dados_limpos`</span>, com o objetivo de avaliar a estrutura das variáveis e conferir os resultados obtidos após o processo de limpeza.</span>
<span id="cb39-427"><a href="#cb39-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-428"><a href="#cb39-428" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-429"><a href="#cb39-429" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados_limpos)</span>
<span id="cb39-430"><a href="#cb39-430" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_limpos)</span>
<span id="cb39-431"><a href="#cb39-431" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-432"><a href="#cb39-432" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-433"><a href="#cb39-433" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados_limpos)</span>
<span id="cb39-434"><a href="#cb39-434" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_limpos)</span>
<span id="cb39-435"><a href="#cb39-435" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-436"><a href="#cb39-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-437"><a href="#cb39-437" aria-hidden="true" tabindex="-1"></a>A partir da aplicação da função <span class="in">`str()`</span>, verificou-se que a base de dados tratada agora é composta por 95 observações e 10 variáveis. Após o processo de limpeza, as variáveis quantitativas foram adequadamente convertidas para o tipo numérico (num), enquanto as variáveis qualitativas permaneceram armazenadas como caracteres (chr).</span>
<span id="cb39-438"><a href="#cb39-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-439"><a href="#cb39-439" aria-hidden="true" tabindex="-1"></a>Por meio da função <span class="in">`summary()`</span>, foi possível verificar o comportamento das variáveis após as correções realizadas. Observa-se que os valores anteriormente identificados como discrepantes foram tratados, resultando em intervalos mais coerentes para as variáveis analisadas. A idade dos corpos de prova passou a variar entre 7 e 56 dias, o abatimento entre 64 e 175 mm, a densidade entre 2.293 e 2.464 kg/m³ e a absorção de água do agregado entre 0,80% e 2,92%.</span>
<span id="cb39-440"><a href="#cb39-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-441"><a href="#cb39-441" aria-hidden="true" tabindex="-1"></a>Além disso, as variáveis resistência à compressão, consumo de cimento e relação água/cimento apresentaram valores entre 19,0 e 47,5 MPa, 295 e 418 kg/m³ e 0,43 e 0,65, respectivamente. Dessa forma, a nova inspeção indica que as inconsistências identificadas nas etapas anteriores foram corrigidas, tornando a base mais adequada para as análises subsequentes.</span>
<span id="cb39-442"><a href="#cb39-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-443"><a href="#cb39-443" aria-hidden="true" tabindex="-1"></a><span class="fu">### Exploração dos dados</span></span>
<span id="cb39-444"><a href="#cb39-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-445"><a href="#cb39-445" aria-hidden="true" tabindex="-1"></a>Após o tratamento da base de dados, procedeu-se à análise estatística descritiva da resistência à compressão dos corpos de prova.</span>
<span id="cb39-446"><a href="#cb39-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-447"><a href="#cb39-447" aria-hidden="true" tabindex="-1"></a>Para a resistência média geral foi utilizado a função <span class="in">`mean()`</span></span>
<span id="cb39-448"><a href="#cb39-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-449"><a href="#cb39-449" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb39-450"><a href="#cb39-450" aria-hidden="true" tabindex="-1"></a>media_resistencia <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_limpos<span class="sc">$</span>resistencia_mpa)</span>
<span id="cb39-451"><a href="#cb39-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-452"><a href="#cb39-452" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-453"><a href="#cb39-453" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb39-454"><a href="#cb39-454" aria-hidden="true" tabindex="-1"></a>media_resistencia <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_limpos<span class="sc">$</span>resistencia_mpa)</span>
<span id="cb39-455"><a href="#cb39-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-456"><a href="#cb39-456" aria-hidden="true" tabindex="-1"></a>media_resistencia</span>
<span id="cb39-457"><a href="#cb39-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-458"><a href="#cb39-458" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-459"><a href="#cb39-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-460"><a href="#cb39-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-461"><a href="#cb39-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-462"><a href="#cb39-462" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🧠 Considerações finais</span></span>
<span id="cb39-463"><a href="#cb39-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-464"><a href="#cb39-464" aria-hidden="true" tabindex="-1"></a>Apresente uma síntese dos principais pontos observados no experimento.</span>
<span id="cb39-465"><a href="#cb39-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-466"><a href="#cb39-466" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Retome o objetivo da prática e indique se ele foi alcançado.</span>
<span id="cb39-467"><a href="#cb39-467" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Destaque os principais aprendizados obtidos.</span>
<span id="cb39-468"><a href="#cb39-468" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Comente brevemente sobre a qualidade dos dados coletados.</span>
<span id="cb39-469"><a href="#cb39-469" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Sugira possíveis melhorias no procedimento experimental.</span>
<span id="cb39-470"><a href="#cb39-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-471"><a href="#cb39-471" aria-hidden="true" tabindex="-1"></a>Evite repetir apenas os resultados; foque nas **conclusões e reflexões** sobre a `variaveis prática realizada.</span>
<span id="cb39-472"><a href="#cb39-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-473"><a href="#cb39-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-474"><a href="#cb39-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-475"><a href="#cb39-475" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📖 Referências</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>